server:
 port: 8200
spring:
 application:
  name: icv-ms-vehicle
 cloud:
  config:
   server:
    git:
     uri: https://github.com/shansr/icv-ms-config.git     #配置远端GitServer的地址
     username: ssr_sdu@126.com
     password: suiji@126
